management.endpoints.web.exposure.include: health

spring:
  application:
    name: my-movies

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true